# ----------- CONFIGURABLE START -----------
title: "Hayden J GitHub blog"
description: "Full Stack | AI"
url: https://jhy156456.github.io
signoff: "HaydenJ" # Your name
timezone: Asia/Seoul
encoding: "euc-kr"

# Analytics
analytics:
  provider: "google-gtag" # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id: "G-S9G62LP1GS"
    anonymize_ip: # true, false (default)
# google_analytics: G-S9G62LP1GS
# google_analytics:
  # tracking_id: "G-S9G62LP1GS"

share: true
future: true

# Plugins (previously gems:)
plugins:
  - jekyll-paginate-v2

links:
  - name: 홈
    url: /
    external: false
  - name: 리뷰
    url: /review
    external: false
  - name: 카테고리
    url: /study
    external: false
  - name: 기록
    url: /archives
  #   external:     false
  # - name:         标签
  #   url:          /tags
  #   external:     false
  - name: About Me
    url: /about
    external: false
# ------------ CONFIGURABLE END ------------
pagination:
  enabled: true
  paginate: 15
  per_page: 12
  # permalink: "jhy156456page:num"

permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
      image_url: ""

category_archive:
  type: liquid
  path: /categories/

#markdown: kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge

# tag_archive:
#   type: liquid
#   path: /tags/

#   # Sass/SCSS
# sass:
#   sass_dir: _sass
#   style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
