# ----------- CONFIGURABLE START -----------
title:            "Hayden J GitHub blog"
description:      "Full Stack | AI"
url:              https://jhy156456.github.io 
signoff:          "HaydenJ" # Your name
facebook_appid:   #liberxue
# google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "jhy156456page:num"
gems: [jekyll-paginate]
links:
  - name:         홈
    url:          /
    external:     false
  - name:         연구
    url:          /book
    external:     false
  - name:         공부
    url:          /study
    external:     false
  - name:         기록
    url:          /archives
  #   external:     false
  # - name:         标签
  #   url:          /tags
  #   external:     false
  - name:         about me
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"




category_archive:
  type: liquid
  path: /categories/
# tag_archive:
#   type: liquid
#   path: /tags/

#   # Sass/SCSS
# sass:
#   sass_dir: _sass
#   style: compressed # https://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style